version: "3"

services:
  server :
    image: server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    networks:
      - webnet

  prometheus:
    build: .
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml   
    depends_on:
      - server
    networks:
      - webnet 
    command: ['prom/prometheus:v2.40.7']

  grafana:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - webnet 
    command: ['grafana/grafana:9.4.2']

volumes:
  logs:
  conf:

networks:
  webnet:
